# Python continuous integration (CI) workflow. The workflow runs tests to ensure the integrity
# of the codebase's content, and linters to ensure the consistency of its format.

name: Python CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  python_ci:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Install dependencies
        run: |
          poetry install --no-root
          source .venv/bin/activate

      - name: Run tests
        run: poetry run inv test -c

      - name: Run linters
        run: poetry run inv lint -c
